---
- name: Check variables
  debug:
    msg: "item={{ item }}"
  loop:
    - certificate

- name: Create a directory if it does not exist
  file:
    path: "{{ certificate.directory }}"
    state: directory
    mode: '0700'
